server:
  port: 8999
logging:
  level:
    org:
      springframework:
        web: INFO

spring: 
  h2: 
    console: 
      enabled: true
      path: /h2

  datasource: 
    url: jdbc:h2:file:~/shipwreck11
    user: sa
    password: pass
    driver-class-name: org.h2.Driver

flyway: 
  baseline-on-migration: true

hibernate: 
  hbm2ddl: 
    auto: false
